# Generated by Django 5.1.4 on 2024-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area_ensenanza',
            field=models.CharField(blank=True, choices=[('salud', 'Salud'), ('cultura', 'Cultura'), ('ciencia', 'Ciencia')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
